name: C/C++ CI

on:
  push:
    branches: [ "1-2568(2025)" ]
  pull_request:
    branches: [ "1-2568(2025)" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug - List CPP files
        run: find . -name "*.cpp"

      - name: Compile
        working-directory: ./CPP
        run: g++ *.cpp -o main

      - name: Run
        run: ./main
